### ISSUE TITLE
CMS Routes do not call theme middleware

### ISSUE THREAD

**Issue by starsinmypockets** [datopian/frontend-v2#129]
CMS routes never call theme middleware - as a result theme variables defined via `res.locals` are not available in theme base-templates, etc.

**Comment by anuveyatsu** [comment]
@starsinmypockets there is a way to do it: https://github.com/datopian/frontend-v2/blob/master/themes/opendk/index.js#L23-L48

**Comment by anuveyatsu** [comment]
Basically, the order is:

1. Plugin routes
2. Theme routes
3. Core routes

CMS routes were calling `res.render` method and finishing the response so theme controllers never called.

We already doing some fixes, e.g.,:

https://github.com/datopian/frontend-v2/commit/a657d7874bed58e5d0fb68ceb68ff29fb844fe09#diff-00ba1bab034fd58d5a96700a38818a08

I'm closing this issue because:

- a workaround is provided
- a fix for some of the routes already implemented
