### ISSUE TITLE
WP plugin `getPost` new signature

### ISSUE THREAD

**Issue by EvgeniiaVak** [datopian/frontend-v2#164]
There was a recent update in WP CmsModel class, method `getPost`:

this:
https://github.com/datopian/frontend-v2/blob/9a4a4e373f190361e46b56140bbcc190aa0569e6/plugins/wp/cms.js#L14

became this:
https://github.com/datopian/frontend-v2/blob/df45207d986ad0dc20e6c5cbf68f8b597404014f/plugins/wp/cms.js#L17

now a simple use such as:
```
cmsModel.getPost(`myPostSlug`)
```
won't work, you have to specify object instead of a string:
```
cmsModel.getPost({slug: `myPostSlug`})
```

Is the change necessary? Can we make it still work with just string slugs?
e.g.
```
 async getPost(slug, params = {}) {
```

If not, are we safe that no client app will be broken by this? Meaning do we have client frontend-v2 instances referencing the v1.1.0 tag but not master branch?

**Comment by anuveyatsu** [comment]
Hey @EvgeniiaVak great that you've raised this. It is necessary as we want to be able to get draft posts where needed. I understand that it can break some of the existing projects so we can release a new version specifying that it contains a breaking change.

Generally, I suggest upgrading the project's code to use a new signature because it will add a new feature to preview the posts/pages in the draft status so that you can test it prior to publishing.

**Comment by EvgeniiaVak** [comment]
Got it. Thank you @anuveyatsu
