### ISSUE TITLE
Custom route shouldn't override CMS routes

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/frontend-v2#33]
E.g., if I define a custom route controller for `/:parent/:page` it overrides the CMS pages such as `/news/:post` which I don't really want to happen.

This is where we define CMS and DMS routes: https://github.com/datopian/frontend-v2/blob/master/index.js#L69-L72

**Comment by anuveyatsu** [comment]
This can be fixed by doing the following:

```javascript
// E.g., I don't want to override paths where parent is equal to 'news'
module.exports = function (app) {
  app.get('/:owner/:name', async (req, res, next) => {
    if (req.params.parent === 'news') {
      next()
      return
    }

    ...
  })
}
```

**Comment by georgiana-b** [comment]
I reopened this because I thought the proposed solution doesn't work. I was using:

```js
    if (req.params.parent === 'news') {
```

but then I realized I need to replace `parent` with whatever route we our trying to avoid, in our case `collections`.

It doesn't feel very clean but I did some research and didn't find anything more promising so we'll go with that and close this again.
